<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="14.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SistemaEstudiantes.Application\SistemaEstudiantes.Application.csproj" />
    <ProjectReference Include="..\SistemaEstudiantes.Infrastructure\SistemaEstudiantes.Infrastructure.csproj" />
  </ItemGroup>

</Project>
