apiVersion: apps/v1
kind: Deployment
metadata:
  name: wf-students
  namespace: sample-app-namespace-1762220734102
  labels:
    app.kubernetes.io/name: wf-students
    kubernetes.azure.com/generator: devhub
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: wf-students
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wf-students
    spec:
      containers:
        - name: wf-students
          image: registry1762219187865.azurecr.io/image-workflow-1762220734058:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          envFrom:
            - configMapRef:
                name: wf-students-config
                optional: true   # evita fallo si aún no existe
            - secretRef:
                name: secret-ref
                optional: true
          readinessProbe:
            tcpSocket: { port: 8080 }
            initialDelaySeconds: 3
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 1
            successThreshold: 1
          livenessProbe:
            tcpSocket: { port: 8080 }
            initialDelaySeconds: 5
            periodSeconds: 10
          startupProbe:
            tcpSocket: { port: 8080 }
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
          securityContext:
            seccompProfile: { type: RuntimeDefault }
            capabilities:
              drop: [ "ALL" ]
              add:
                - SETPCAP
                - MKNOD
                - AUDIT_WRITE
                - CHOWN
                - DAC_OVERRIDE
                - FOWNER
                - FSETID
                - KILL
                - SETGID
                - SETUID
                - NET_BIND_SERVICE
                - SYS_CHROOT
                - SETFCAP
                - SYS_PTRACE
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: wf-students
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: wf-students
