apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: wf-students
  labels:
    app.kubernetes.io/name: wf-students
    app.kubernetes.io/part-of: wf-students-project
    kubernetes.azure.com/generator: devhub
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: wf-students