apiVersion: v1
kind: Service
metadata:
  name: wf-students
  namespace: sample-app-namespace-1762220734102
  labels:
    app.kubernetes.io/name: wf-students
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: wf-students
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80