// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaEstudiantes.Infrastructure.Data;

#nullable disable

namespace SistemaEstudiantes.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250224060228_RequiredIDProgramFromUserQuited2")]
    partial class RequiredIDProgramFromUserQuited2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaEstudiantes.Domain.Entities.Materia", b =>
                {
                    b.Property<int>("IDMateria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDMateria"));

                    b.Property<int>("Creditos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(3);

                    b.Property<int>("IDProfesor")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IDMateria");

                    b.HasIndex("IDProfesor");

                    b.ToTable("Materias", (string)null);

                    b.HasData(
                        new
                        {
                            IDMateria = 1,
                            Creditos = 3,
                            IDProfesor = 1,
                            Nombre = "Programación I"
                        },
                        new
                        {
                            IDMateria = 2,
                            Creditos = 3,
                            IDProfesor = 1,
                            Nombre = "Programación II"
                        },
                        new
                        {
                            IDMateria = 3,
                            Creditos = 3,
                            IDProfesor = 2,
                            Nombre = "Bases de Datos"
                        },
                        new
                        {
                            IDMateria = 4,
                            Creditos = 3,
                            IDProfesor = 2,
                            Nombre = "Sistemas Operativos"
                        },
                        new
                        {
                            IDMateria = 5,
                            Creditos = 3,
                            IDProfesor = 3,
                            Nombre = "Redes de Computadoras"
                        },
                        new
                        {
                            IDMateria = 6,
                            Creditos = 3,
                            IDProfesor = 3,
                            Nombre = "Seguridad Informática"
                        },
                        new
                        {
                            IDMateria = 7,
                            Creditos = 3,
                            IDProfesor = 4,
                            Nombre = "Arquitectura de Computadoras"
                        },
                        new
                        {
                            IDMateria = 8,
                            Creditos = 3,
                            IDProfesor = 4,
                            Nombre = "Inteligencia Artificial"
                        },
                        new
                        {
                            IDMateria = 9,
                            Creditos = 3,
                            IDProfesor = 5,
                            Nombre = "Desarrollo Web"
                        },
                        new
                        {
                            IDMateria = 10,
                            Creditos = 3,
                            IDProfesor = 5,
                            Nombre = "Ingeniería de Software"
                        });
                });

            modelBuilder.Entity("SistemaEstudiantes.Domain.Entities.Profesor", b =>
                {
                    b.Property<int>("IDProfesor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDProfesor"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IDProfesor");

                    b.ToTable("Profesores", (string)null);

                    b.HasData(
                        new
                        {
                            IDProfesor = 1,
                            Nombre = "Carlos Gómez"
                        },
                        new
                        {
                            IDProfesor = 2,
                            Nombre = "Ana Rodríguez"
                        },
                        new
                        {
                            IDProfesor = 3,
                            Nombre = "Luis Fernández"
                        },
                        new
                        {
                            IDProfesor = 4,
                            Nombre = "María López"
                        },
                        new
                        {
                            IDProfesor = 5,
                            Nombre = "Javier Pérez"
                        });
                });

            modelBuilder.Entity("SistemaEstudiantes.Domain.Entities.Programa", b =>
                {
                    b.Property<int>("IDPrograma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDPrograma"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IDPrograma");

                    b.ToTable("Programas", (string)null);

                    b.HasData(
                        new
                        {
                            IDPrograma = 1,
                            Nombre = "Ingeniería de Sistemas"
                        });
                });

            modelBuilder.Entity("SistemaEstudiantes.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("IDUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDUsuario"));

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("IDPrograma")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IDUsuario");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IDPrograma");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("SistemaEstudiantes.Domain.Entities.UsuarioMateria", b =>
                {
                    b.Property<int>("IDUsuarioMateria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDUsuarioMateria"));

                    b.Property<int>("IDMateria")
                        .HasColumnType("int");

                    b.Property<int>("IDUsuario")
                        .HasColumnType("int");

                    b.HasKey("IDUsuarioMateria");

                    b.HasIndex("IDMateria");

                    b.HasIndex("IDUsuario");

                    b.ToTable("UsuarioMaterias", (string)null);
                });

            modelBuilder.Entity("SistemaEstudiantes.Domain.Entities.Materia", b =>
                {
                    b.HasOne("SistemaEstudiantes.Domain.Entities.Profesor", "Profesor")
                        .WithMany("Materias")
                        .HasForeignKey("IDProfesor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profesor");
                });

            modelBuilder.Entity("SistemaEstudiantes.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("SistemaEstudiantes.Domain.Entities.Programa", "Programa")
                        .WithMany("Usuarios")
                        .HasForeignKey("IDPrograma")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Programa");
                });

            modelBuilder.Entity("SistemaEstudiantes.Domain.Entities.UsuarioMateria", b =>
                {
                    b.HasOne("SistemaEstudiantes.Domain.Entities.Materia", "Materia")
                        .WithMany("UsuarioMaterias")
                        .HasForeignKey("IDMateria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaEstudiantes.Domain.Entities.Usuario", "Usuario")
                        .WithMany("UsuarioMaterias")
                        .HasForeignKey("IDUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Materia");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaEstudiantes.Domain.Entities.Materia", b =>
                {
                    b.Navigation("UsuarioMaterias");
                });

            modelBuilder.Entity("SistemaEstudiantes.Domain.Entities.Profesor", b =>
                {
                    b.Navigation("Materias");
                });

            modelBuilder.Entity("SistemaEstudiantes.Domain.Entities.Programa", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("SistemaEstudiantes.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("UsuarioMaterias");
                });
#pragma warning restore 612, 618
        }
    }
}
