// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaEstudiantes.Infrastructure.Data;

#nullable disable

namespace SistemaEstudiantes.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250223221246_ProgramaEntityAdded2")]
    partial class ProgramaEntityAdded2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaEstudiantes.Domain.Entities.Materia", b =>
                {
                    b.Property<int>("IDMateria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDMateria"));

                    b.Property<int>("Creditos")
                        .HasColumnType("int");

                    b.Property<int>("IDProfesor")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IDMateria");

                    b.HasIndex("IDProfesor");

                    b.ToTable("Materias", (string)null);
                });

            modelBuilder.Entity("SistemaEstudiantes.Domain.Entities.Profesor", b =>
                {
                    b.Property<int>("IDProfesor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDProfesor"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IDProfesor");

                    b.ToTable("Profesores", (string)null);
                });

            modelBuilder.Entity("SistemaEstudiantes.Domain.Entities.Programa", b =>
                {
                    b.Property<int>("IDPrograma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDPrograma"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IDPrograma");

                    b.ToTable("Programas", (string)null);
                });

            modelBuilder.Entity("SistemaEstudiantes.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("IDUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDUsuario"));

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("IDPrograma")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IDUsuario");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IDPrograma");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("SistemaEstudiantes.Domain.Entities.UsuarioMateria", b =>
                {
                    b.Property<int>("IDUsuarioMateria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDUsuarioMateria"));

                    b.Property<int>("IDMateria")
                        .HasColumnType("int");

                    b.Property<int>("IDUsuario")
                        .HasColumnType("int");

                    b.HasKey("IDUsuarioMateria");

                    b.HasIndex("IDMateria");

                    b.HasIndex("IDUsuario");

                    b.ToTable("UsuarioMaterias", (string)null);
                });

            modelBuilder.Entity("SistemaEstudiantes.Domain.Entities.Materia", b =>
                {
                    b.HasOne("SistemaEstudiantes.Domain.Entities.Profesor", "Profesor")
                        .WithMany("Materias")
                        .HasForeignKey("IDProfesor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profesor");
                });

            modelBuilder.Entity("SistemaEstudiantes.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("SistemaEstudiantes.Domain.Entities.Programa", "Programa")
                        .WithMany("Usuarios")
                        .HasForeignKey("IDPrograma")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Programa");
                });

            modelBuilder.Entity("SistemaEstudiantes.Domain.Entities.UsuarioMateria", b =>
                {
                    b.HasOne("SistemaEstudiantes.Domain.Entities.Materia", "Materia")
                        .WithMany("UsuarioMaterias")
                        .HasForeignKey("IDMateria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaEstudiantes.Domain.Entities.Usuario", "Usuario")
                        .WithMany("UsuarioMaterias")
                        .HasForeignKey("IDUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Materia");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaEstudiantes.Domain.Entities.Materia", b =>
                {
                    b.Navigation("UsuarioMaterias");
                });

            modelBuilder.Entity("SistemaEstudiantes.Domain.Entities.Profesor", b =>
                {
                    b.Navigation("Materias");
                });

            modelBuilder.Entity("SistemaEstudiantes.Domain.Entities.Programa", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("SistemaEstudiantes.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("UsuarioMaterias");
                });
#pragma warning restore 612, 618
        }
    }
}
